-- ═══════════════════════════════════════════════════════════════════════════
-- CLASS SOCIAL — LEARNING LOOP: bình luận + nhận xét của Thầy (tag kiến thức,
-- đính kèm bài giảng Kho) + kiểm duyệt mềm. CHƯA CHẠY. Idempotent.
-- Chạy SAU db/class_social_posts_setup.sql. Rollback: db/class_social_learning_loop_rollback.sql.
--
-- Vai trò (audit): app_users.role ∈ admin|teacher|team_leader|truong_nhom|student|guest.
-- Quy ước sẵn có của repo: admin BAO HÀM teacher → dùng public.is_teacher() (teacher|admin)
-- cho badge THẦY, tạo tag, đính kèm bài giảng, kiểm duyệt. KHÔNG đổi role của ai.
--
-- Nhận xét của Thầy VẪN LÀ bình luận; tag + đính kèm là metadata tách bảng (bình luận
-- thường vẫn nhẹ). Tag là dữ liệu có cấu trúc (bảng + join), không phải chuỗi phẩy.
-- Kiểm duyệt MỀM: hidden_at/hidden_by trên bài + bình luận (không xoá cứng), chỉ qua RPC
-- dành cho thầy; trigger chặn tác giả tự sửa cờ ẩn.
-- ═══════════════════════════════════════════════════════════════════════════

-- 1) Kiểm duyệt mềm cho bài đăng
alter table public.class_posts add column if not exists hidden_at timestamptz;
alter table public.class_posts add column if not exists hidden_by uuid references auth.users(id) on delete set null;

create or replace function public.class_posts_before_update()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.author_user_id := old.author_user_id;
  new.created_at     := old.created_at;
  new.updated_at     := now();
  if not public.is_teacher() then          -- chỉ thầy (qua RPC kiểm duyệt) đổi được cờ ẩn
    new.hidden_at := old.hidden_at;
    new.hidden_by := old.hidden_by;
  end if;
  return new;
end $$;

-- Bài bị ẩn: chỉ thầy còn thấy (để bỏ ẩn); học sinh — kể cả tác giả — không thấy
drop policy if exists class_posts_member_read on public.class_posts;
create policy class_posts_member_read on public.class_posts
  for select to authenticated
  using (public.is_class_member() and (hidden_at is null or public.is_teacher()));

-- 2) Bình luận
create table if not exists public.class_post_comments (
  id                uuid primary key default gen_random_uuid(),
  seq               bigint generated by default as identity,   -- thứ tự ghi — sắp hội thoại chính xác kể cả khi trùng giờ
  post_id           uuid not null references public.class_posts(id) on delete cascade,
  parent_comment_id uuid references public.class_post_comments(id) on delete cascade,  -- dành cho trả lời (chưa có UI)
  author_user_id    uuid not null default auth.uid() references auth.users(id) on delete cascade,
  body              text not null,
  hidden_at         timestamptz,
  hidden_by         uuid references auth.users(id) on delete set null,
  created_at        timestamptz not null default clock_timestamp(),
  updated_at        timestamptz not null default clock_timestamp()
);
-- clock_timestamp() (không phải now() = đầu giao dịch): thứ tự hội thoại luôn đúng thời điểm ghi
alter table public.class_post_comments alter column created_at set default clock_timestamp();
alter table public.class_post_comments alter column updated_at set default clock_timestamp();
alter table public.class_post_comments drop constraint if exists class_post_comments_body_check;
alter table public.class_post_comments add constraint class_post_comments_body_check
  check (char_length(btrim(body)) between 1 and 2000);
create index if not exists class_post_comments_post_idx on public.class_post_comments (post_id, seq);
create index if not exists class_post_comments_author_idx on public.class_post_comments (author_user_id, created_at desc);

-- Bài còn hiển thị với người đang hỏi (member + chưa ẩn, hoặc là thầy)
create or replace function public.class_post_visible(p_post_id uuid)
returns boolean language sql security definer set search_path = '' stable as $$
  select public.is_class_member() and exists (
    select 1 from public.class_posts p
    where p.id = p_post_id and (p.hidden_at is null or public.is_teacher())
  );
$$;
revoke all on function public.class_post_visible(uuid) from public, anon;
grant execute on function public.class_post_visible(uuid) to authenticated;

create or replace function public.class_post_comments_before_write()
returns trigger language plpgsql set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    new.body := btrim(new.body);
    new.hidden_at := null; new.hidden_by := null;
    -- trả lời phải cùng bài
    if new.parent_comment_id is not null and not exists (
      select 1 from public.class_post_comments c where c.id = new.parent_comment_id and c.post_id = new.post_id
    ) then
      raise exception 'parent_comment_id không thuộc bài này' using errcode = '23514';
    end if;
    return new;
  end if;
  new.id                := old.id;
  new.seq               := old.seq;
  new.post_id           := old.post_id;
  new.parent_comment_id := old.parent_comment_id;
  new.author_user_id    := old.author_user_id;
  new.created_at        := old.created_at;
  new.body              := btrim(new.body);
  new.updated_at        := now();
  if not public.is_teacher() then
    new.hidden_at := old.hidden_at;
    new.hidden_by := old.hidden_by;
  end if;
  return new;
end $$;
drop trigger if exists class_post_comments_before_write on public.class_post_comments;
create trigger class_post_comments_before_write before insert or update on public.class_post_comments
  for each row execute function public.class_post_comments_before_write();

alter table public.class_post_comments enable row level security;
revoke all on public.class_post_comments from anon;
grant select, insert, update, delete on public.class_post_comments to authenticated;

drop policy if exists cpc_member_read on public.class_post_comments;
create policy cpc_member_read on public.class_post_comments
  for select to authenticated
  using (public.class_post_visible(post_id) and (hidden_at is null or public.is_teacher()));
drop policy if exists cpc_own_insert on public.class_post_comments;
create policy cpc_own_insert on public.class_post_comments
  for insert to authenticated
  with check (author_user_id = auth.uid() and public.class_post_visible(post_id));
drop policy if exists cpc_own_update on public.class_post_comments;
create policy cpc_own_update on public.class_post_comments
  for update to authenticated
  using (author_user_id = auth.uid()) with check (author_user_id = auth.uid());
drop policy if exists cpc_own_delete on public.class_post_comments;
create policy cpc_own_delete on public.class_post_comments
  for delete to authenticated
  using (author_user_id = auth.uid());

-- 3) Tag kiến thức — CHỈ thầy tạo. Không trùng khác hoa/thường (unique lower(name)).
create table if not exists public.class_tags (
  id         bigint generated by default as identity primary key,
  name       text not null,
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table public.class_tags drop constraint if exists class_tags_name_check;
alter table public.class_tags add constraint class_tags_name_check
  check (char_length(name) between 1 and 40 and name !~ '[[:space:]#,<>"''`]');
create unique index if not exists class_tags_name_lower_uq on public.class_tags (lower(name));

alter table public.class_tags enable row level security;
revoke all on public.class_tags from anon;
grant select, insert on public.class_tags to authenticated;
drop policy if exists class_tags_member_read on public.class_tags;
create policy class_tags_member_read on public.class_tags
  for select to authenticated using (public.is_class_member());
drop policy if exists class_tags_teacher_insert on public.class_tags;
create policy class_tags_teacher_insert on public.class_tags
  for insert to authenticated with check (public.is_teacher() and created_by = auth.uid());

create table if not exists public.class_comment_tags (
  comment_id uuid   not null references public.class_post_comments(id) on delete cascade,
  tag_id     bigint not null references public.class_tags(id) on delete cascade,
  primary key (comment_id, tag_id)
);
create index if not exists class_comment_tags_tag_idx on public.class_comment_tags (tag_id);  -- "mọi nhận xét #Nhịp"

alter table public.class_comment_tags enable row level security;
revoke all on public.class_comment_tags from anon;
grant select, insert, delete on public.class_comment_tags to authenticated;
drop policy if exists cct_member_read on public.class_comment_tags;
create policy cct_member_read on public.class_comment_tags
  for select to authenticated using (public.is_class_member());
-- Thầy gắn tag vào bình luận CỦA CHÍNH MÌNH
drop policy if exists cct_teacher_insert on public.class_comment_tags;
create policy cct_teacher_insert on public.class_comment_tags
  for insert to authenticated with check (
    public.is_teacher()
    and exists (select 1 from public.class_post_comments c where c.id = comment_id and c.author_user_id = auth.uid())
  );
drop policy if exists cct_teacher_delete on public.class_comment_tags;
create policy cct_teacher_delete on public.class_comment_tags
  for delete to authenticated using (
    public.is_teacher()
    and exists (select 1 from public.class_post_comments c where c.id = comment_id and c.author_user_id = auth.uid())
  );

-- 4) Đính kèm tài nguyên học tập vào bình luận của thầy — CHỈ LƯU THAM CHIẾU, không chép video/nội dung.
--    Quyền xem bài giảng do Kho quyết định khi học sinh mở link (Kho middleware + requireKhoAccess).
--    resource_type 'kho_video': resource_id = kho_videos.video_id (ID YouTube — khoá chính ổn định
--      của Kho). Link: /khobaigiang/video/<id>?t=<start_seconds>. Player của Kho CHƯA hỗ trợ điểm
--      kết thúc → end_seconds để dành (UI P2 không dùng).
--    title_snapshot: tiêu đề lúc thầy đính kèm. BẢN CHỤP bắt buộc phải có vì học sinh chưa được cấp
--      quyền Kho không đọc được kho_videos (RLS thầy-only, API trả 403) → không resolve sạch được.
--    excerpt: đoạn trích NGẮN thầy tự chọn — BẢN CHỤP, không phải nội dung gốc (transcript Kho
--      không có định danh đoạn; chỉ có mốc giây).
create table if not exists public.class_comment_resources (
  id            uuid primary key default gen_random_uuid(),
  comment_id    uuid not null references public.class_post_comments(id) on delete cascade,
  resource_type text not null,
  resource_id   text not null,
  title_snapshot text,
  start_seconds int,
  end_seconds   int,
  excerpt       text,
  sort_order    smallint not null default 0,
  created_at    timestamptz not null default now()
);
alter table public.class_comment_resources drop constraint if exists class_comment_resources_type_check;
alter table public.class_comment_resources add constraint class_comment_resources_type_check
  check (resource_type in ('kho_video'));
alter table public.class_comment_resources drop constraint if exists class_comment_resources_id_check;
alter table public.class_comment_resources add constraint class_comment_resources_id_check
  check (resource_id ~ '^[A-Za-z0-9_-]{1,64}$');
alter table public.class_comment_resources drop constraint if exists class_comment_resources_seg_check;
alter table public.class_comment_resources add constraint class_comment_resources_seg_check
  check ((start_seconds is null or start_seconds between 0 and 86400)
     and (end_seconds is null or (start_seconds is not null and end_seconds > start_seconds and end_seconds <= 86400)));
alter table public.class_comment_resources drop constraint if exists class_comment_resources_excerpt_check;
alter table public.class_comment_resources add constraint class_comment_resources_excerpt_check
  check (excerpt is null or char_length(excerpt) between 1 and 500);
alter table public.class_comment_resources add column if not exists title_snapshot text;
alter table public.class_comment_resources drop constraint if exists class_comment_resources_title_check;
alter table public.class_comment_resources add constraint class_comment_resources_title_check
  check (title_snapshot is null or char_length(title_snapshot) between 1 and 200);
create index if not exists class_comment_resources_comment_idx on public.class_comment_resources (comment_id, sort_order);
create index if not exists class_comment_resources_res_idx on public.class_comment_resources (resource_type, resource_id);

alter table public.class_comment_resources enable row level security;
revoke all on public.class_comment_resources from anon;
grant select, insert, delete on public.class_comment_resources to authenticated;
drop policy if exists ccr_member_read on public.class_comment_resources;
create policy ccr_member_read on public.class_comment_resources
  for select to authenticated using (public.is_class_member());
drop policy if exists ccr_teacher_insert on public.class_comment_resources;
create policy ccr_teacher_insert on public.class_comment_resources
  for insert to authenticated with check (
    public.is_teacher()
    and exists (select 1 from public.class_post_comments c where c.id = comment_id and c.author_user_id = auth.uid())
  );
drop policy if exists ccr_teacher_delete on public.class_comment_resources;
create policy ccr_teacher_delete on public.class_comment_resources
  for delete to authenticated using (
    public.is_teacher()
    and exists (select 1 from public.class_post_comments c where c.id = comment_id and c.author_user_id = auth.uid())
  );

-- 5) Gửi bình luận (kèm tag/đính kèm) trong MỘT giao dịch. SECURITY INVOKER → mọi RLS ở trên
--    vẫn áp đúng người gọi (học sinh gửi tag/đính kèm sẽ bị chặn).
--    p_resources: [{resource_type, resource_id, title_snapshot?, start_seconds?, end_seconds?, excerpt?}]
create or replace function public.class_add_comment(
  p_post_id   uuid,
  p_body      text,
  p_tag_ids   bigint[] default '{}',
  p_resources jsonb    default '[]'::jsonb,
  p_parent_id uuid     default null
)
returns uuid language plpgsql security invoker set search_path = '' as $$
declare v_id uuid; r jsonb; i int := 0;
begin
  insert into public.class_post_comments (post_id, parent_comment_id, body)
  values (p_post_id, p_parent_id, p_body)
  returning id into v_id;

  if coalesce(array_length(p_tag_ids, 1), 0) > 0 then
    if array_length(p_tag_ids, 1) > 10 then raise exception 'Tối đa 10 tag' using errcode = '23514'; end if;
    insert into public.class_comment_tags (comment_id, tag_id)
    select v_id, t from (select distinct unnest(p_tag_ids) as t) x;
  end if;

  if jsonb_typeof(p_resources) = 'array' and jsonb_array_length(p_resources) > 0 then
    if jsonb_array_length(p_resources) > 5 then raise exception 'Tối đa 5 tài nguyên' using errcode = '23514'; end if;
    for r in select * from jsonb_array_elements(p_resources) loop
      insert into public.class_comment_resources (comment_id, resource_type, resource_id, title_snapshot, start_seconds, end_seconds, excerpt, sort_order)
      values (v_id, r->>'resource_type', r->>'resource_id', nullif(btrim(r->>'title_snapshot'), ''),
              nullif(r->>'start_seconds', '')::int, nullif(r->>'end_seconds', '')::int,
              nullif(btrim(r->>'excerpt'), ''), i);
      i := i + 1;
    end loop;
  end if;
  return v_id;
end $$;
revoke all on function public.class_add_comment(uuid, text, bigint[], jsonb, uuid) from public, anon;
grant execute on function public.class_add_comment(uuid, text, bigint[], jsonb, uuid) to authenticated;

-- 6) Kiểm duyệt (ẩn / bỏ ẩn) — CHỈ thầy/admin
create or replace function public.class_moderate(p_kind text, p_id uuid, p_hidden boolean)
returns void language plpgsql security definer set search_path = '' as $$
begin
  if not public.is_teacher() then raise exception 'Không có quyền' using errcode = '42501'; end if;
  if p_kind = 'post' then
    update public.class_posts set hidden_at = case when p_hidden then now() end,
                                  hidden_by = case when p_hidden then auth.uid() end
     where id = p_id;
  elsif p_kind = 'comment' then
    update public.class_post_comments set hidden_at = case when p_hidden then now() end,
                                          hidden_by = case when p_hidden then auth.uid() end
     where id = p_id;
  else
    raise exception 'p_kind không hợp lệ' using errcode = '22023';
  end if;
  if not found then raise exception 'Không tìm thấy' using errcode = 'P0002'; end if;
end $$;
revoke all on function public.class_moderate(text, uuid, boolean) from public, anon;
grant execute on function public.class_moderate(text, uuid, boolean) to authenticated;

-- 7) Danh tính công khai dùng chung (tên hiển thị + avatar + vai trò) — không email/SĐT
create or replace function public.class_public_identity(p_user_id uuid)
returns table(name text, avatar_url text, role text, ht_member boolean)
language sql security definer set search_path = '' stable as $$
  select coalesce(
           nullif(split_part(trim(s.display_name), '@', 1), ''),
           nullif(split_part(trim(s.full_name), '@', 1), ''),
           nullif(split_part(trim(au.name), '@', 1), ''),
           'Thành viên Class'),
         s.avatar_url,
         case when au.role in ('teacher', 'admin') then 'teacher' else 'student' end,
         coalesce(s.ht_member, false)
  from (select p_user_id as uid) x
  left join lateral (
    select es.display_name, es.full_name, es.avatar_url, es.ht_member
    from public.edu_students es where es.user_id = x.uid
    order by es.enrolled_at desc nulls last limit 1
  ) s on true
  left join public.app_users au on au.id = x.uid;
$$;
revoke all on function public.class_public_identity(uuid) from public, anon, authenticated;  -- chỉ dùng nội bộ RPC

-- 8) Feed: bỏ bài bị ẩn (trừ thầy), thêm is_hidden + comment_count. Đổi kiểu trả về → drop/create.
drop function if exists public.class_feed(timestamptz, uuid, int);
create function public.class_feed(
  p_before    timestamptz default null,
  p_before_id uuid        default null,
  p_limit     int         default 20
)
returns table(
  id uuid, type text, body text,
  media_type text, media_provider text, media_url text, external_media_id text,
  created_at timestamptz, updated_at timestamptz,
  author_user_id uuid, author_name text, author_avatar_url text,
  author_role text, author_ht_member boolean, is_mine boolean,
  is_hidden boolean, comment_count int
)
language sql security definer set search_path = '' stable as $$
  select p.id, p.type, p.body,
         p.media_type, p.media_provider, p.media_url, p.external_media_id,
         p.created_at, p.updated_at,
         p.author_user_id, idn.name, idn.avatar_url, idn.role, idn.ht_member,
         p.author_user_id = auth.uid(),
         p.hidden_at is not null,
         (select count(*)::int from public.class_post_comments c
           where c.post_id = p.id and (c.hidden_at is null or public.is_teacher()))
  from public.class_posts p
  cross join lateral public.class_public_identity(p.author_user_id) idn
  where public.is_class_member()
    and (p.hidden_at is null or public.is_teacher())
    and (
      p_before is null
      or p.created_at < p_before
      or (p.created_at = p_before and p_before_id is not null and p.id < p_before_id)
    )
  order by p.created_at desc, p.id desc
  limit least(greatest(coalesce(p_limit, 20), 1), 50);
$$;
revoke all on function public.class_feed(timestamptz, uuid, int) from public, anon;
grant execute on function public.class_feed(timestamptz, uuid, int) to authenticated;

-- 9) Bình luận của nhiều bài trong MỘT lần gọi (không N+1): kèm danh tính công khai,
--    tag, đính kèm (chỉ tham chiếu). Lấy p_per_post bình luận MỚI NHẤT mỗi bài (feed: 3;
--    "Xem thêm bình luận": tối đa 200), trả về theo thứ tự CŨ → MỚI. Tối đa 50 bài/lần.
drop function if exists public.class_comments_for_posts(uuid[]);
create or replace function public.class_comments_for_posts(p_post_ids uuid[], p_per_post int default 3)
returns table(
  id uuid, post_id uuid, parent_comment_id uuid, body text,
  created_at timestamptz, updated_at timestamptz,
  author_user_id uuid, author_name text, author_avatar_url text, author_role text,
  is_mine boolean, is_hidden boolean, tags jsonb, resources jsonb,
  post_comment_count int     -- tổng bình luận (đang hiển thị) của bài — để hiện "Xem thêm (N)"
)
language sql security definer set search_path = '' stable as $$
  select c.id, c.post_id, c.parent_comment_id, c.body, c.created_at, c.updated_at,
         c.author_user_id, idn.name, idn.avatar_url, idn.role,
         c.author_user_id = auth.uid(), c.hidden_at is not null,
         coalesce((select jsonb_agg(jsonb_build_object('id', t.id, 'name', t.name) order by t.name)
                     from public.class_comment_tags ct join public.class_tags t on t.id = ct.tag_id
                    where ct.comment_id = c.id), '[]'::jsonb),
         coalesce((select jsonb_agg(jsonb_build_object(
                      'id', r.id, 'resource_type', r.resource_type, 'resource_id', r.resource_id, 'title', r.title_snapshot,
                      'start_seconds', r.start_seconds, 'end_seconds', r.end_seconds, 'excerpt', r.excerpt)
                    order by r.sort_order)
                     from public.class_comment_resources r where r.comment_id = c.id), '[]'::jsonb),
         (select count(*)::int from public.class_post_comments c2
           where c2.post_id = p.id and (c2.hidden_at is null or public.is_teacher()))
  from (select unnest(p_post_ids[1:50]) as pid) ids
  join public.class_posts p on p.id = ids.pid
  cross join lateral (
    select * from public.class_post_comments c0
    where c0.post_id = p.id and (c0.hidden_at is null or public.is_teacher())
    order by c0.seq desc
    limit least(greatest(coalesce(p_per_post, 3), 1), 200)
  ) c
  cross join lateral public.class_public_identity(c.author_user_id) idn
  where public.is_class_member()
    and (p.hidden_at is null or public.is_teacher())
  order by c.post_id, c.seq;
$$;
revoke all on function public.class_comments_for_posts(uuid[], int) from public, anon;
grant execute on function public.class_comments_for_posts(uuid[], int) to authenticated;

notify pgrst, 'reload schema';
