-- ═══════════════════════════════════════════════════════════════════════════
-- MÔ HÌNH LỚP MỚI (09/2026) — CHƯA CHẠY. Idempotent phần lớn; chạy CÙNG LÚC deploy landing mới.
--   A. Lớp cửa vào (T3): Guitar căn bản 1 / 2 — chạy liên tục, mỗi "vòng" 4 buổi.
--   B. Lớp chính (T4): Solo Guitar · Đệm hát nâng cao — tồn tại lâu dài theo slot.
--   C. Chặng: nội dung lớp đang học (class_stages) — tên công khai + khoá của chặng.
-- Không đụng: T5 (SOLO01.TH01, HT2027.TH01), 2 lớp T6 đang học, học viên, gói, IAP, billing,
-- course_prereqs (đang chặn tiên quyết cho học viên HT — lộ trình mới chỉ nằm ở nội dung tư vấn).
-- ═══════════════════════════════════════════════════════════════════════════

-- 0) Chốt an toàn: 6 lớp theo phương án cũ phải còn RỖNG mới được huỷ
do $$ declare n int; begin
  select count(*) into n from edu_group_members m join class_schedule c on c.group_id = m.group_id
   where c.code in ('DH1.KD20','TN1.GL14','DH2.KD21','TN2.GL15','SOLO01.TH02','DHNC01.TH01');
  if n > 0 then raise exception 'Lớp cũ đã có % thành viên — dừng', n; end if;
  select count(*) into n from edu_course_access a
   where a.note ~ '(DH1\.KD20|TN1\.GL14|DH2\.KD21|TN2\.GL15|SOLO01\.TH02|DHNC01\.TH01)';
  if n > 0 then raise exception 'Lớp cũ đã cấp % quyền — dừng', n; end if;
end $$;

-- 1) public_product: thêm 2 lớp cửa vào (giữ mọi key cũ để tương thích)
alter table public.class_schedule drop constraint if exists class_schedule_public_product_chk;
alter table public.class_schedule add constraint class_schedule_public_product_chk
  check (public_product is null or public_product in
    ('guitar_can_ban_1','guitar_can_ban_2','solo_guitar','dem_hat_nang_cao',
     'dem_hat_can_ban','guitar_can_ban','dem_hat_trung_cap','guitar_trung_cap'));

-- 2) Chặng của lớp — CHỈ là lịch nội dung của một lớp vật lý (không phải hệ curriculum):
--    buổi from..to thuộc chặng nào, tên công khai lúc đó, khoá được mở khi vào lớp ở chặng đó.
create table if not exists public.class_stages (
  id           bigint generated by default as identity primary key,
  class_id     uuid not null references public.class_schedule(id) on delete cascade,
  stage_no     int  not null check (stage_no >= 1),
  public_title text not null,
  course_id    uuid references public.edu_courses(id),
  from_session int  not null,
  to_session   int  not null,
  starts_on    date,            -- ngày buổi đầu chặng (suy từ class_sessions, để landing đọc không cần buổi)
  ends_on      date,            -- ngày buổi cuối chặng
  created_at   timestamptz not null default now(),
  unique (class_id, stage_no),
  check (from_session >= 1 and to_session >= from_session)
);
alter table public.class_stages enable row level security;
drop policy if exists cst_read on public.class_stages;
drop policy if exists cst_teacher_write on public.class_stages;
create policy cst_read on public.class_stages for select to anon, authenticated using (true);
create policy cst_teacher_write on public.class_stages for all to authenticated
  using (coalesce(public.is_teacher(), false)) with check (coalesce(public.is_teacher(), false));
-- NHỚ: class_stages nằm trong self_managed của db/rls_setup.sql.

-- 3) Hai khoá mới cho lớp cửa vào (chưa có nội dung → 'coming_soon' tới khi Thầy soạn xong và bật)
insert into public.edu_courses (name, code, status, is_free, type, sort_order, description)
select v.name, v.code, 'coming_soon', false, 'hanh_trinh', v.so, v.d
from (values ('Guitar căn bản 1', 'CB1', 1, 'Bạn chưa biết gì về Guitar? Bắt đầu từ đây.'),
             ('Guitar căn bản 2', 'CB2', 2, 'Bạn đã học Guitar một thời gian nhưng vẫn chưa tiến bộ như mong muốn? Vào lớp để củng cố những phần còn yếu, học thêm những kỹ năng mới và đưa khả năng chơi Guitar lên một mức cao hơn.'))
  v(name, code, so, d)
where not exists (select 1 from public.edu_courses c where c.code = v.code);

-- 4) Huỷ mềm 6 lớp theo phương án cũ (rỗng) — giữ dòng + lịch sử
update public.class_schedule set status = 'cancelled', public_enroll = false
 where code in ('DH1.KD20','TN1.GL14','DH2.KD21','TN2.GL15','SOLO01.TH02','DHNC01.TH01') and status <> 'cancelled';
update public.class_sessions set status = 'cancelled', note = coalesce(note || ' · ', '') || 'Huỷ 09/2026: chuyển sang mô hình lớp mới'
 where class_id in (select id from public.class_schedule where code in ('DH1.KD20','TN1.GL14','DH2.KD21','TN2.GL15','SOLO01.TH02','DHNC01.TH01'))
   and status not in ('completed','cancelled');

-- 5) Nhóm (≡ mã lớp) + 4 lớp mới. course_ids RỖNG: quyền nội dung đến từ gói theo chặng.
insert into public.edu_groups (code, name, group_type, is_active)
select v.code, v.code, 'zalo', true from (values ('CB1.T3'),('CB2.T3'),('SOLO.T4'),('DEM.T4')) v(code)
where not exists (select 1 from public.edu_groups g where upper(g.code) = v.code);

insert into public.class_schedule (code, name, section, schedule, start_text, duration, course_ids, main_course_id, group_id,
  sort_order, is_active, start_date, weekday, start_time, duration_minutes, total_sessions, status, timezone, breaks_after,
  show_on_practice_schedule, metadata, public_product, public_enroll)
select v.code, v.name, 'upcoming', v.sched, to_char(v.sd, 'DD/MM/YYYY'), v.tot || ' buổi · mỗi buổi 90 phút', '{}',
  (select id from public.edu_courses where code = v.course), (select id from public.edu_groups where upper(code) = v.code limit 1),
  0, true, v.sd, v.wd, v.t::time, 90, v.tot, 'upcoming', 'Asia/Ho_Chi_Minh', v.brk, false, '{}'::jsonb, v.product, true
from (values
  ('CB1.T3',  'Guitar căn bản 1', 'CB1',  2, '19:00', date '2026-10-06', 48, null::int[],        'guitar_can_ban_1', 'Thứ 3 · 19h00'),
  ('CB2.T3',  'Guitar căn bản 2', 'CB2',  2, '20:30', date '2026-10-06', 48, null::int[],        'guitar_can_ban_2', 'Thứ 3 · 20h30'),
  ('SOLO.T4', 'Solo Guitar',      'SOLO', 3, '19:00', date '2026-10-14', 24, array[8,16]::int[], 'solo_guitar',      'Thứ 4 · 19h00'),
  ('DEM.T4',  'Đệm hát nâng cao', 'DH2',  3, '20:30', date '2026-10-14', 24, array[8,16]::int[], 'dem_hat_nang_cao', 'Thứ 4 · 20h30')
) v(code, name, course, wd, t, sd, tot, brk, product, sched)
where not exists (select 1 from public.class_schedule c where c.code = v.code);

-- 6) Sinh buổi theo đúng luật hệ thống: bỏ class_off_days, nghỉ 2 tuần sau các buổi breaks_after.
do $$
declare c record; d date; n int; b int[]; bi int; lessons int; stage_title text;
begin
  for c in select * from public.class_schedule where code in ('CB1.T3','CB2.T3','SOLO.T4','DEM.T4') loop
    if exists (select 1 from public.class_sessions where class_id = c.id) then continue; end if;
    d := c.start_date; lessons := 0; b := coalesce(c.breaks_after, '{}');
    while lessons < c.total_sessions loop
      if lessons = any(b) then
        b := array_remove(b, lessons);
        for bi in 1..2 loop
          insert into public.class_sessions (class_id, session_number, start_at, end_at, event_type, status)
          values (c.id, null, (d + c.start_time) at time zone 'Asia/Ho_Chi_Minh', ((d + c.start_time) at time zone 'Asia/Ho_Chi_Minh') + interval '90 minutes', 'break', 'holiday');
          d := d + 7;
        end loop;
        continue;
      end if;
      if exists (select 1 from public.class_off_days o where o.is_active and o.off_date = d) then d := d + 7; continue; end if;
      lessons := lessons + 1;
      insert into public.class_sessions (class_id, session_number, start_at, end_at, event_type, status)
      values (c.id, lessons, (d + c.start_time) at time zone 'Asia/Ho_Chi_Minh', ((d + c.start_time) at time zone 'Asia/Ho_Chi_Minh') + interval '90 minutes', 'lesson', 'scheduled');
      d := d + 7;
    end loop;
    update public.class_schedule set end_date = (select max((start_at at time zone 'Asia/Ho_Chi_Minh')::date) from public.class_sessions where class_id = c.id and event_type = 'lesson')
     where id = c.id;
  end loop;
end $$;

-- 7) Chặng. Lớp cửa vào: mỗi vòng 4 buổi = 1 chặng, tên công khai không đổi. Lớp chính: 3 chặng × 8 buổi.
insert into public.class_stages (class_id, stage_no, public_title, course_id, from_session, to_session)
select c.id, s.no, s.title, (select id from public.edu_courses where code = s.course), s.f, s.t
from public.class_schedule c
join (
  select 'CB1.T3' code, g no, 'Guitar căn bản 1' title, 'CB1' course, (g-1)*4+1 f, g*4 t from generate_series(1,12) g
  union all select 'CB2.T3', g, 'Guitar căn bản 2', 'CB2', (g-1)*4+1, g*4 from generate_series(1,12) g
  union all values ('SOLO.T4', 1, 'Solo Guitar 1', 'SOLO', 1, 8), ('SOLO.T4', 2, 'Solo Guitar 2', 'SOLO', 9, 16), ('SOLO.T4', 3, 'Solo Guitar 3', 'SOLO', 17, 24),
                   ('DEM.T4', 1, 'Đệm hát 2', 'DH2', 1, 8), ('DEM.T4', 2, 'Đệm hát 3', 'DH3', 9, 16), ('DEM.T4', 3, 'Đệm hát nâng cao', 'DHNC', 17, 24)
) s(code, no, title, course, f, t) on s.code = c.code
on conflict (class_id, stage_no) do nothing;
update public.class_stages st set
  starts_on = (select min((s.start_at at time zone 'Asia/Ho_Chi_Minh')::date) from public.class_sessions s where s.class_id = st.class_id and s.event_type = 'lesson' and s.session_number between st.from_session and st.to_session),
  ends_on   = (select max((s.start_at at time zone 'Asia/Ho_Chi_Minh')::date) from public.class_sessions s where s.class_id = st.class_id and s.event_type = 'lesson' and s.session_number between st.from_session and st.to_session)
where st.class_id in (select id from public.class_schedule where code in ('CB1.T3','CB2.T3','SOLO.T4','DEM.T4'));
-- Tên buổi: "Vòng k · Buổi j" cho lớp cửa vào (quay lại Buổi 1 mỗi vòng); "Chặng · Buổi" cho lớp chính.
update public.class_sessions s set title =
  case when c.code like 'CB_.T3' then 'Vòng ' || st.stage_no || ' · Buổi ' || (s.session_number - st.from_session + 1)
       else st.public_title || ' · Buổi ' || (s.session_number - st.from_session + 1) end
from public.class_schedule c, public.class_stages st
where s.class_id = c.id and st.class_id = c.id and c.code in ('CB1.T3','CB2.T3','SOLO.T4','DEM.T4')
  and s.event_type = 'lesson' and s.session_number between st.from_session and st.to_session and s.title is null;

-- 8) Kích hoạt gói: khoá cấp = khoá của CHẶNG đang học (buổi sắp tới), không còn cố định theo lớp.
create or replace function public.class_current_course(p_class uuid)
returns uuid language sql stable security definer set search_path = '' as $$
  select coalesce(
    (select st.course_id from public.class_stages st
      where st.class_id = p_class and st.course_id is not null
        and st.to_session >= coalesce((select min(s.session_number) from public.class_sessions s
                                        where s.class_id = p_class and s.event_type = 'lesson' and s.status = 'scheduled' and s.end_at > now()), 1)
      order by st.stage_no limit 1),
    (select main_course_id from public.class_schedule where id = p_class));
$$;
revoke all on function public.class_current_course(uuid) from public, anon;
grant execute on function public.class_current_course(uuid) to authenticated;

create or replace function public.activate_class_membership(p_lead bigint)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  v_lead public.leads; v_plan text; v_code text; v_cls public.class_schedule; v_pkg public.packages;
  v_course text; v_uid uuid; v_req uuid; v_sp bigint; v_old public.student_packages; v_done boolean := false;
begin
  if not coalesce(public.is_teacher(), false) then raise exception 'Chỉ Thầy/Admin được kích hoạt'; end if;
  select * into v_lead from public.leads where id = p_lead for update;
  if v_lead.id is null then raise exception 'Không tìm thấy đăng ký #%', p_lead; end if;
  if v_lead.student_id is null then raise exception 'Đăng ký chưa gắn tài khoản học viên'; end if;
  v_plan := (regexp_match(coalesce(v_lead.note, ''), '\[plan:(monthly|six_month)\]'))[1];
  if v_plan is null then raise exception 'Đăng ký không có [plan:…] — không thuộc mô hình membership mới'; end if;
  v_code := upper((regexp_match(coalesce(v_lead.class_name, ''), '·\s*([A-Za-z0-9]+\.[A-Za-z0-9]+)\s*$'))[1]);
  if v_code is null then raise exception 'Không đọc được mã lớp trong đăng ký'; end if;
  select * into v_cls from public.class_schedule where upper(code) = v_code limit 1;
  if v_cls.id is null or v_cls.public_product is null then raise exception 'Lớp % không thuộc mô hình tuyển sinh mới', v_code; end if;
  if v_cls.group_id is null then raise exception 'Lớp % chưa có nhóm', v_code; end if;
  -- 09/2026: khoá của CHẶNG đang học (class_stages), lùi về khoá chính nếu lớp chưa khai báo chặng
  select code into v_course from public.edu_courses where id = public.class_current_course(v_cls.id);
  if v_course is null then raise exception 'Lớp % chưa có khoá cho chặng hiện tại', v_code; end if;
  select * into strict v_pkg from public.packages
   where package_code = case v_plan when 'monthly' then 'CLASS_MONTHLY' else 'CLASS_SIXMONTH' end and status = 'active';
  select user_id into v_uid from public.edu_students where id = v_lead.student_id;
  if v_uid is null then raise exception 'Học viên chưa có tài khoản đăng nhập'; end if;

  perform pg_advisory_xact_lock(hashtextextended(v_lead.student_id::text, 0));
  v_req := md5('class-membership:lead:' || p_lead)::uuid;
  select id into v_sp from public.student_packages
   where student_id = v_lead.student_id and external_transaction_id = 'admin-request:' || v_req;
  if v_sp is not null then
    v_done := true;
  else
    select * into v_old from public.student_packages
     where student_id = v_lead.student_id and package_id = v_pkg.id and status = 'active' and entitlement_id is null
     order by renews_at desc nulls last limit 1;
    if v_old.id is null then
      v_sp := public.manage_student_package(v_lead.student_id, 'grant', v_pkg.id, null, null, 'admin', array[v_course], v_req);
    else
      v_sp := public.manage_student_package(v_lead.student_id, 'renew', null, v_old.id, null, 'admin',
        array(select distinct unnest(coalesce(v_old.granted_course_codes, '{}') || array[v_course])), v_req);
    end if;
  end if;

  -- Vào nhóm lớp (xác định lớp). course_ids của lớp mới rỗng ⇒ trigger không cấp quyền vĩnh viễn.
  insert into public.edu_group_members (user_id, group_id, source, status)
  values (v_uid, v_cls.group_id, 'membership', 'active')
  on conflict (user_id, group_id) do update set status = 'active';

  update public.leads set status = 'Đã đóng phí' where id = p_lead and status is distinct from 'Đã đóng phí';

  return jsonb_build_object(
    'already_done', v_done, 'student_package_id', v_sp, 'package_code', v_pkg.package_code, 'plan', v_plan,
    'class_code', v_cls.code, 'course_code', v_course,
    'renews_at', (select renews_at from public.student_packages where id = v_sp),
    'granted_codes', (select to_jsonb(granted_course_codes) from public.student_packages where id = v_sp),
    'zalo_url', (select zalo_url from public.edu_groups where id = v_cls.group_id));
end $$;
revoke all on function public.activate_class_membership(bigint) from public, anon;
grant execute on function public.activate_class_membership(bigint) to authenticated;

notify pgrst, 'reload schema';
