-- Fixture Learning Thread P1 cho cluster PostgreSQL TẠM (scripts/test-learning-threads-db.sh). KHÔNG chạy production.
-- Nạp SAU social_fixture.sql + migration Social. Giả lập đúng các cột production (preflight 29/09) mà RPC mới đọc:
-- giáo trình (khoá → chương → bài), journey_curriculum, lớp (class_schedule/class_stages + nhóm cohort),
-- và my_learning_state() — bản giả trả ĐÚNG hợp đồng production {courses:[{lessons:[{id, access}]}]}
-- (quyền mở bài lấy từ bảng t_access để test điều khiển được).

create table public.edu_courses (
  id uuid primary key default gen_random_uuid(), name text not null, code text, track text, status text default 'on'
);
create table public.edu_modules (
  id uuid primary key default gen_random_uuid(),
  course_id uuid references public.edu_courses(id) on delete cascade,
  name text not null, order_index int default 0, level int
);
create table public.edu_course_lessons (
  id uuid primary key default gen_random_uuid(),
  module_id uuid not null references public.edu_modules(id) on delete cascade,
  title text not null, lesson_type text default 'video', order_index int default 0
);
create table public.edu_lesson_progress (
  id uuid primary key default gen_random_uuid(), student_id uuid, lesson_id uuid references public.edu_course_lessons(id) on delete cascade,
  status text default 'completed'
);
create table public.journey_tracks (key text primary key, title text not null);
create table public.journey_curriculum (
  course_id uuid primary key references public.edu_courses(id) on delete cascade,
  subject text not null references public.journey_tracks(key), level int not null default 1
);
create table public.class_schedule (
  id uuid primary key default gen_random_uuid(), code text, name text not null, program_code text, stage text,
  public_product text, status text not null default 'active', main_course_id uuid, course_ids uuid[] not null default '{}',
  start_date date, cohort_group_id uuid references public.edu_groups(id) on delete restrict
);
create table public.class_stages (
  id bigint generated by default as identity primary key,
  class_id uuid not null references public.class_schedule(id) on delete cascade,
  stage_no int not null, public_title text not null, course_id uuid references public.edu_courses(id),
  starts_on date, ends_on date
);

-- Quyền mở bài (thay cho gói/entitlement thật): (user, bài) → access
create table public.t_access (user_id uuid, lesson_id uuid, access text, primary key (user_id, lesson_id));
create or replace function public.my_learning_state()
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'mode', case when public.is_teacher() then 'teacher' when auth.uid() is not null then 'student' else 'guest' end,
    'courses', coalesce((
      select jsonb_agg(jsonb_build_object('id', c.id, 'code', c.code, 'lessons', coalesce((
        select jsonb_agg(jsonb_build_object('id', l.id,
                 'access', case when public.is_teacher() then 'open'
                                else coalesce((select a.access from public.t_access a where a.user_id = auth.uid() and a.lesson_id = l.id), 'upgrade') end))
        from public.edu_course_lessons l join public.edu_modules m on m.id = l.module_id where m.course_id = c.id), '[]'::jsonb)))
      from public.edu_courses c), '[]'::jsonb));
$$;

-- Dữ liệu: khoá DH2 (Đệm hát 2) · Chương 4 Bolero · 4 bài; khoá khác TN1 · 1 bài
insert into public.journey_tracks values ('dem_hat', 'Đệm hát'), ('tia_not', 'Tỉa nốt');
insert into public.edu_courses (id, name, code, track) values
  ('c0000000-0000-4000-8000-0000000000d2', 'Khởi Đầu Đam Mê – Đệm Hát Trình Độ 2', 'DH2', 'dem_hat'),
  ('c0000000-0000-4000-8000-0000000000a1', 'Tỉa nốt 1', 'TN1', 'tia_not');
insert into public.journey_curriculum values ('c0000000-0000-4000-8000-0000000000d2', 'dem_hat', 2);
insert into public.edu_modules (id, course_id, name, order_index, level) values
  ('d0000000-0000-4000-8000-000000000044', 'c0000000-0000-4000-8000-0000000000d2', 'Chương 4: Điệu Bolero & kỹ thuật móc', 3, 2),
  ('d0000000-0000-4000-8000-0000000000a1', 'c0000000-0000-4000-8000-0000000000a1', 'Chặng 1', 0, 2);
insert into public.edu_course_lessons (id, module_id, title, lesson_type, order_index) values
  ('e0000000-0000-4000-8000-000000000001', 'd0000000-0000-4000-8000-000000000044', 'Bài 4.3 — Bolero móc kiểu 1', 'video', 2),
  ('e0000000-0000-4000-8000-000000000002', 'd0000000-0000-4000-8000-000000000044', 'Bài 4.7 — Nền tập Bolero', 'strum', 6),
  ('e0000000-0000-4000-8000-000000000003', 'd0000000-0000-4000-8000-000000000044', 'Bài 4.1 — Tính chất Bolero', 'text', 0),
  ('e0000000-0000-4000-8000-000000000004', 'd0000000-0000-4000-8000-000000000044', 'Bài 4.8 — Gảy theo Bolero', 'text', 7),
  ('e0000000-0000-4000-8000-0000000000a1', 'd0000000-0000-4000-8000-0000000000a1', 'Bài 1: Nốt Mi đầu tiên', 'flow', 0);

-- Lớp DH2.KD18 (nhóm cohort) đang dạy DH2 ở chặng 1; A thuộc lớp. B, C tự học.
insert into public.edu_groups (id, name, group_type, code) values
  ('f0000000-0000-4000-8000-0000000000c1', 'DH2.KD18', 'class', 'DH2.KD18');
insert into public.class_schedule (id, code, name, program_code, stage, public_product, status, main_course_id, start_date, cohort_group_id) values
  ('b0000000-0000-4000-8000-0000000000c1', 'DH2.KD18', 'Đệm hát căn bản — KD18', null, 'co_ban', 'dem_hat_can_ban', 'active',
   'c0000000-0000-4000-8000-0000000000d2', current_date - 30, 'f0000000-0000-4000-8000-0000000000c1');
insert into public.class_stages (class_id, stage_no, public_title, course_id, starts_on, ends_on) values
  ('b0000000-0000-4000-8000-0000000000c1', 1, 'Đệm hát 2', 'c0000000-0000-4000-8000-0000000000d2', current_date - 30, current_date + 30);
insert into public.edu_group_members (user_id, group_id, source, status) values
  ('aaaaaaaa-0000-4000-8000-00000000000a', 'f0000000-0000-4000-8000-0000000000c1', 'admin', 'active');

-- Quyền mở bài: A, B, C mở bài 1–3; bài 4 chỉ B mở (A bị khoá); bài TN1 mở cho A
insert into public.t_access
select u, l, 'open'
from unnest(array['aaaaaaaa-0000-4000-8000-00000000000a', 'bbbbbbbb-0000-4000-8000-00000000000b',
                  'cccccccc-0000-4000-8000-00000000000c']::uuid[]) u,
     unnest(array['e0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-000000000002',
                  'e0000000-0000-4000-8000-000000000003']::uuid[]) l;
insert into public.t_access values
  ('bbbbbbbb-0000-4000-8000-00000000000b', 'e0000000-0000-4000-8000-000000000004', 'open'),
  ('aaaaaaaa-0000-4000-8000-00000000000a', 'e0000000-0000-4000-8000-0000000000a1', 'open');
